server:
  port: ${PORT:0}

spring:
  application:
    name: users-ws
  datasource:
    url: jdbc:mysql://localhost:3380/app?serverTimezone=UTC
    username: test
    password: test
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web

eureka:
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file: users-ws.log
  level:
    br.com.api.users.data.AlbumsServiceClient: DEBUG
  path: /users/login

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: mappings

gateway:
  ip: 192.168.2.81

token:
  expiration_time: 864000000
  secret: hfgry463hf746hf573ydh475fhy5739