server:
  port: 0

spring:
  application:
    name: account-ws
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url: http://localhost:8010/eureka