server:
  port: 8010

spring:
  application:
    name: discoveryservice

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://test:test@localhost:8010/eureka